FileVersion = 1
Dependencies = {corlib = "*", ImGui = "*", ImGuiImplGlfw = "*", ImGuiImplOpenGL3 = "*", VmScriptingFun = "*"}

[Project]
Name = "VmGui"
StartupObject = "VmGui.Program"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"

[Configs.Release.Win64]
CLibType = "Dynamic"
